// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqE1bnowz0ZcPy_T5NzTB8DyHlLPptTdY',
    appId: '1:970953904842:web:4918e435150ea363875a33',
    messagingSenderId: '970953904842',
    projectId: 'echangeplus-7faec',
    authDomain: 'echangeplus-7faec.firebaseapp.com',
    storageBucket: 'echangeplus-7faec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwojzUUCPBn5eO-TQXK0QnCCs2aTcO0SI',
    appId: '1:970953904842:android:f3609dcdb597ee40875a33',
    messagingSenderId: '970953904842',
    projectId: 'echangeplus-7faec',
    storageBucket: 'echangeplus-7faec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAia3sGLiDu_6CklbY4j8Pb0VCyaKIVW0w',
    appId: '1:970953904842:ios:6aed0e939737c1ce875a33',
    messagingSenderId: '970953904842',
    projectId: 'echangeplus-7faec',
    storageBucket: 'echangeplus-7faec.firebasestorage.app',
    iosBundleId: 'com.example.echangePlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAia3sGLiDu_6CklbY4j8Pb0VCyaKIVW0w',
    appId: '1:970953904842:ios:6aed0e939737c1ce875a33',
    messagingSenderId: '970953904842',
    projectId: 'echangeplus-7faec',
    storageBucket: 'echangeplus-7faec.firebasestorage.app',
    iosBundleId: 'com.example.echangePlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqE1bnowz0ZcPy_T5NzTB8DyHlLPptTdY',
    appId: '1:970953904842:web:4c7b47c6be651d7a875a33',
    messagingSenderId: '970953904842',
    projectId: 'echangeplus-7faec',
    authDomain: 'echangeplus-7faec.firebaseapp.com',
    storageBucket: 'echangeplus-7faec.firebasestorage.app',
  );
}
